### PR TITLE
add: new feature PROXY command

### PR DESCRIPTION
**Pull request by TomFreudenberg**
Based on discussion at #49

### CODE REVIEW

**Comment by TomFreudenberg** [comment]
Hi @iuri-gg 

This is my first part of implementation.

Should handle the proxy command if enabled by `:proxy_feature: true` on init.

Valid syntax is:

```
            # syntax
            # PROXY PROTO source-ip dest-ip source-port dest-port
            # supported commands:
            # PROXY TCP4 255.255.255.255 255.255.255.255 65535 65535
            # PROXY TCP6 ffff:f...f:ffff ffff:f...f:ffff 65535 65535
            # PROXY UNKNOWN
            # PROXY UNKNOWN ffff:f...f:ffff ffff:f...f:ffff 65535 65535

```

Any UNKNOWN data are irgnored.

The `when` will check for at least a valid ip v4 or v6 and valid port ranges.

Then a new event is called `on_proxy_event` given all information as a hash.

Finally the default or returned hash from event is added to context at:

`ctx[:server][:proxies]`

The order will be done reversed so that the last proxy information is always stored as element 0 (ZERO)

I do not change the remote_ip or other remote_ information automatically.

Some can use the data from context for expressions or change the remote_ information during proxy event. As anybody like.

Hopefully you may agree to the implementation?

Tests will come afterwards.

Thanks for your feedback


---

P.S.: As an example your current implementation will look like:

```ruby
def on_proxy_event(ctx, proxy_data)
  ctx[:server][:remote_ip] = proxy_data.source_ip
  ctx[:server][:remote_host] = proxy_data.source_ip
  ctx[:server][:remote_port] = proxy_data.source_port
  proxy_data
```

or just do nothing and when logging etc just check

```ruby
def whatever(ctx)
  unless ctx[:server][:proxies].empty?
    puts "This is the client IP: #{ctx[:server][:proxies][0].source_ip}"
  end
end
```

**Comment by TomFreudenberg** [comment]
Hi @iuri-gg 

that is now the implementation from my side

If you will agree I create the documentation and push a new gem

**Comment by TomFreudenberg** [comment]
@gencer - maybe an interesting feature for you as well when coming to scaling and optimizing your platform

**Comment by iuri-gg** [comment]
Thank you @TomFreudenberg for adding the proxy support feature. I just tested it and have a couple of observations for you:

1. when `proxy_extension` is disabled, `PROXY` commands can no longer be handled by `on_process_line_unknown_event`, since now an exception is getting raised instead of calling `on_process_line_unknown_event`. I think this is fine though. 
2. when `proxy_extension` is enabled, STARTTLS is broken and I get `DATA failed: 250` in curl when SSL is disabled. I believe `return '250 OK'` on proxy commands is causing the issue. I edited the server to return `""` (blank string) and everything started working. I believe `haproxy` passes responses back to the client and the client is getting confused by receive `250 OK` especially when pipelining is enabled. 

Hope this helps and please let me know if you need me to test more

**Comment by iuri-gg** [comment]
SSL request:
```
* Connected to localhost (127.0.0.1) port 5555 (#0)
< 220 midi-smtp says welcome!
> EHLO ms-invite.eml
< 250 OK
* STARTTLS not supported.
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
* Closing connection 0
curl: (64) STARTTLS not supported.
```

No SSL request:
```
* Connected to localhost (127.0.0.1) port 5555 (#0)
< 220 midi-smtp says welcome!
> EHLO ms-invite.eml
< 250 OK
> MAIL FROM:<test@test.com>
< 250 OK
> RCPT TO:<test@test.com>
< 250 OK
> DATA
< 250-midi-smtp at your service!
< 250-PIPELINING
< 250-AUTH LOGIN PLAIN
< 250-STARTTLS
< 250 OK
* DATA failed: 250
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
> QUIT
< 530 Authentication required
* Closing connection 0
curl: (55) DATA failed: 250
```

**Comment by TomFreudenberg** [comment]
was manually squashed and merged

**Comment by TomFreudenberg** [comment]
> 2. when `proxy_extension` is enabled, STARTTLS is broken and I get `DATA failed: 250` in curl when SSL is disabled. I believe `return '250 OK'` on proxy commands is causing the issue. 

@iuri-gg could you please reply by `return '249 OK'`

2.?.? is SMTP success message
2.4.? is SMTP network and routing status messages

so that's why I choose "249 OK" => PROXY OK

**Comment by TomFreudenberg** [comment]
Or if fail - maybe we use `209 OK` as status

**Comment by gencer** [comment]
> @gencer - maybe an interesting feature for you as well when coming to scaling and optimizing your platform.

An exciting feature.

Currently, we have our own distribution system (as you are already known). However, making `PROXY` available makes me wonder how we can enable this with existing HAProxy to better align with rest of the system.

Thanks for the ping. I need to look and evaluate this option now.

🚀

**Comment by iuri-gg** [comment]
> Or if fail - maybe we use `209 OK` as status

Same issue with both 249 and 209. I believe we should not send any response back. Those proxy commands are one way - haproxy adds them in the beginning and does not expect reply. any reply gets sent back to the original client and confuses it. 

```
* Connected to localhost (127.0.0.1) port 5555 (#0)
< 220 midi-smtp says welcome!
> EHLO ms-invite.eml
< 249 OK
> MAIL FROM:<test@test.com>
< 249 OK
> RCPT TO:<test@test.com>
< 249 OK
> DATA
< 250-midi-smtp at your service!
< 250-PIPELINING
< 250-AUTH LOGIN PLAIN
< 250-STARTTLS
< 250 OK
* DATA failed: 250
* ```

**Comment by TomFreudenberg** [comment]
Ok, I remove the Output

At least there should be nothing then, even not a line feed?

Will check that

**Comment by TomFreudenberg** [comment]
@iuri-gg - latest master got update with `return ''`

Thanks for feedback and testing

**Pull request closed without merging**
