### PR TITLE
Add a parameter to skip accept loop for enabling forking servers

### PR DESCRIPTION
**Pull request by davidk01**
**Describe the changes**
This change adds an extra parameter to skip starting the accepting thread. The reason is that I would like to bind the TCP connection, fork several processes, and then in each process start the accept loops. This pattern is often used to let the operating system load balance connections to several processes without the need of proxies like HAProxy.

**Test case**
The change is backwards compatible but the way to test that it works would be to initialize the server and then start the accepting threads in forked processes, e.g.
```ruby
server = MidiSmtpServer::Smtpd.new(...)
skip_accept = true
server.start(skip_accept)
n_procs = 2
children = (0...n_procs).map do |_|
  fork do
    server.tcp_servers.each { |s| server.start_accept_thread(s) }
    server.join
  end
end
children.each { |pid| Process.waitpid(pid) }
```

**Expected behavior**
Previous functionality should continue to work as expected and new functionality should be enabled as described above by passing in a parameter to skip starting the acceptance thread.

**System tested on (please complete the following information):**
 - OS: Ubuntu 20.04.4
 - Ruby: 3.0.0

**Additional information**
This is a draft proposal so if there are any changes that need to be made please let me know and I'm happy to make them. Being able to fork and then accept connections would be very useful for reducing operational overhead like deploying HAProxy so I'm motivated to get this merged, I think it would be helpful for other people as well who are interested in deploying a Ruby SMTP server to simplify the management of email servers and workloads.

### CODE REVIEW

**Comment by TomFreudenberg** [comment]
Hi @davidk01 

first thanks for taking time to improve midi-smtp-server with your ideas.

Currently I do not really get what you might want to improve. From my current perspective we create a seperate thread over any incoming valid connection what might let the OS balance the load already.

In addition your proposal will break the limit meter like max-connections etc. In case you double or triple or ... the number of forked processes and TCPservers the limit are multiplied as well.

Could you please figure out what kind of load optimization an OS can do better by children (fork) than threading?

Looking forward to your conversation
Tom

**Comment by davidk01** [comment]
Hi Tom,

Here is a blog post with a good explanation about pre-forking servers that accept connections in child processes: [Linux Applications Performance: Part III: Preforked Servers](https://unixism.net/2019/04/linux-applications-performance-part-iii-preforked-servers/). The relevant section for this PR is the following:

> If there are 10 child processes waiting on accept(), the operating system will, with fairness, equally try to distribute incoming connections among them.

So in pseudo-code this is what happens:
```
parent process binds to a socket
children = n.times do
  fork {
    further set up
    forked child process starts accepting connections
  }
end
wait for children to finish
```

In each child process the number of active connection is respected the same way it would have been in the parent process if it was running by itself but the benefit of the pre-forking model is that once the parent process binds to the socket then that socket can be shared among any number of child processes handling the accept loop and the operating system will fairly distribute the connections among the forked processes. Ruby has a global interpreter lock so if a server has 10 cores then to fully utilize all the cores will require spawning more than one process to listen for connections because threads are not mapped to a processes. Here is a good article explaining some of the implementation details of Ruby's threads: [Ruby threads worth it?](https://medium.com/gympass/ruby-threads-worth-it-46167522142b):

> GIL (Global Interpreter Lock) or GVL (Global VM Lock), act as a lock around Ruby code.
> It allows concurrent execution of Ruby code but prevents parallel execution.
> Each instance of MRI has a GIL. If some of these MRI processes spawn multiple threads, GIL comes in action, preventing parallel execution.

**Comment by TomFreudenberg** [comment]
Hi David,

if I got it right current implementation of midi-smtp-server will use 1 (one) core only regardless an available multi-core cpu and running threads per this one CORE only, handled by Ruby GIL and executed one thread action after next thread action.

So long - not so fancy - is this correct from my understanding?

So we need to append an option to enable more cores by forking processes and let them handle a number of threads per each core (forked process) to handle simultaneously (parallel) sessions.

Is this correct?

If my assumptions are correct, then I would prefer to implement the preforking feature directly handled by midi-smtp-server library and append an additional config option like: 

```ruby
# +max_processings+:: maximum number of simultaneous processed connections PER CORE/FORK, this does not limit the number of concurrent TCP connections. Default value = DEFAULT_SMTPD_MAX_PROCESSINGS
# +max_connections+:: maximum number of connections PER CORE/FORK, this does limit the number of concurrent TCP connections (not set or nil => unlimited)

# +max_fork+:: maximum number of child processes (FORK) to handle connections preforked and in parallel on multiple processes/cores orchestrated by operating system (not set or nil => single process) 
```

**Comment by davidk01** [comment]
Hi Tom,

Your understanding is correct. I think handling the forking directly by the server is a good solution. I'll close this PR for the time being.

**Pull request closed without merging**
